services:
  emulator:
    build:
      context: ./emulator
      dockerfile: Dockerfile
      args:
        - FIREBASE_VERSION=13.3.3
    stop_grace_period: 1m
    environment:
      FIREBASE_AUTH_EMULATOR_HOST: 'localhost:9099'
      FIRESTORE_EMULATOR_HOST: 'localhost:8080'
      PUBSUB_EMULATOR_HOST: 'localhost:8085'
      FUNCTIONS_EMULATOR_HOST: 'localhost:5001'
      FIREBASE_PROJECT: 'test-project'
      GCLOUD_PROJECT: 'test-project'
      FORCE_COLOR: 'true'
      DATA_DIRECTORY: 'data'
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - '4000:4000' # ui
      - '4400:4400' # hub
      - '4600:4600' # logging
      - '5001:5001' # functions
      - '8080:8080' # firestore
      - '8085:8085' # pubsub
      - '9000:9000' # database
      - '9099:9099' # auth
      - '9199:9199' # Storage
      - '6000:6000' # Hosting
    volumes:
      - ./firebase:/srv/firebase:rw
      - ./cache:/root/.cache/:rw
      - ~/.config/:/root/.config
      - ./firebase/data:/srv/firebase/data:rw
